name: "Example-ci"
on: [push]
jobs:
    example-job:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - run: echo "hello"
            - uses: subosito/flutter-action@v2
              with:
                channel: 'stable'
            - run: flutter analyze .